name: 03 - Workflow Runner

on: push

jobs:
    ubuntu-runner:
        runs-on: ubuntu-latest
        steps:
            - name: Show OS
              run: |
                  echo "This job is running on an Ubuntu runner!"
                  echo "Runner OS: $RUNNER_OS"
    windows-runner:
        runs-on: windows-latest
        steps:
            - name: Show OS
              shell: bash
              run: |
                  echo "This job is running on an Windows runner!"
                  echo "Runner OS: $RUNNER_OS"
    mac-runner:
        runs-on: mac-latest
        steps:
            - name: Show OS
              run: | 
                  echo "This job is running on an Mac runner!"
                  echo "Runner OS: $RUNNER_OS"
